baseURL = 'https://yuushaexa.github.io/vnovel'
languageCode = 'en-us'
title = "GameLibrary"
theme = "database"  
disableKinds = ['rss']
[params]
    description = "Games Library"
    author = "Yuusha"
    [security]
[security.gotemplates]
allowActionJSTmpl = true
[pagination]
  pagerSize = 50
[services]
    [services.rss]
       limit = 5
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[taxonomies]
    tag = "tags"
    category = "categories"
    developers = "developers"
    genres = "genres"
[outputs]
    page = [ 'html' ]
    taxonomy = [ "HTML" ]
    term = [ "HTML" ]

